cask_args appdir: '/Applications'

tap 'homebrew/cask-fonts'
tap 'homebrew/bundle'

brew 'ack'
brew 'asdf'
brew 'awscli'
brew 'bash-completion'
brew 'composer'
brew 'coreutils'
brew 'ctags-exuberant'
brew 'curl'
brew 'diff-so-fancy'
brew 'gist'
brew 'git'
brew 'go'
brew 'jq'
brew 'libtool'
brew 'macvim'
brew 'mysql@5.7'
brew 'node'
brew 'pre-commit'
# brew 'php@7.3'
brew 'python3'
brew 'cairo'
brew 'pango'
brew 'openssl'
brew 'readline'
# brew 'redis'
brew 'sqlite'
# brew 'terminal-notifier'
# brew 'testdisk'
brew 'tree'
brew 'wget'
# brew 'xz'
brew 'zlib'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'

cask '1password'
# cask 'alt-tab'
# cask 'authy'
# cask 'atom'
# cask 'cyberduck'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-drive-file-stream'
cask 'iterm2'
# cask 'jetbrains-toolbox'
cask 'kaleidoscope'
cask 'lastpass'
cask 'mysqlworkbench'
cask 'paw'
cask 'postman'
cask 'sequel-pro'
cask 'spotify'
cask 'slack'
cask 'textmate'
cask 'tunnelblick'
# cask 'vagrant'
# cask 'virtualbox'
cask 'visual-studio-code'
cask 'visual-studio-code-insiders'


# app store
mas 'amphetamine', id: 937984704
mas 'microsoft-onenote', id: 784801555
# mas 'microsoft-remote-desktop', id: 715768417
mas 'onedrive', id: 823766827
# mas 'xcode', id: 497799835

# fonts
cask 'font-hack'
cask 'font-fira-code'
